name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      run: |
        # Android SDK 설치
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools
        unzip -q commandlinetools-linux-9477386_latest.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        
        # 환경 변수 설정
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # 라이센스 수락
        yes | sdkmanager --licenses
        
        # 필요한 패키지 설치
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
    
    - name: Create Local Properties
      run: |
        echo "sdk.dir=$PWD/android-sdk" > local.properties
    
    - name: Setup Gradle
      run: |
        # Gradle Wrapper 생성
        mkdir -p gradle/wrapper
        
        # gradle-wrapper.jar 다운로드
        wget https://github.com/gradle/gradle/raw/v7.6.0/gradle/wrapper/gradle-wrapper.jar -O gradle/wrapper/gradle-wrapper.jar
        
        # gradlew 스크립트 다운로드
        wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradlew -O gradlew
        chmod +x gradlew
        
        # gradlew.bat 다운로드 (Windows용)
        wget https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradlew.bat -O gradlew.bat
    
    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      run: |
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        ./gradlew assembleDebug --warning-mode all --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: KakaoAutoSender
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
