name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Create gradle wrapper
      run: |
        # Gradle Wrapper 파일 생성
        mkdir -p gradle/wrapper
        
        # gradle-wrapper.properties 생성
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOF
        
        # gradlew 실행 파일 다운로드
        curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew > gradlew
        chmod +x gradlew
        
        # gradlew.bat 다운로드 (Windows용)
        curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew.bat > gradlew.bat
    
    - name: Download Gradle Wrapper JAR
      run: |
        mkdir -p gradle/wrapper
        curl -L https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar > gradle/wrapper/gradle-wrapper.jar
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon
      
    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 90
        
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Development Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: dev-${{ github.run_number }}
        name: Development Build ${{ github.run_number }}
        files: app/build/outputs/apk/debug/app-debug.apk
        prerelease: true
        generate_release_notes: true
